/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Feedback { 'message' : string, 'timestamp' : bigint }
export type Language = { 'en' : null } |
  { 'nl' : null } |
  { 'pl' : null } |
  { 'th' : null } |
  { 'zh' : null };
export interface PasswordEntry {
  'url' : string,
  'title' : string,
  'username' : Username,
  'blob' : [] | [ExternalBlob],
  'password' : StrongPassword,
  'notes' : string,
}
export interface SecureNote {
  'title' : string,
  'content' : string,
  'blob' : [] | [ExternalBlob],
}
export type StrongPassword = string;
export interface UserProfile { 'name' : string, 'language' : Language }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Username = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPasswordEntryToVault' : ActorMethod<
    [string, Username, StrongPassword, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'addSecureNoteToVault' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePasswordEntryFromVault' : ActorMethod<[string], undefined>,
  'deleteSecureNoteFromVault' : ActorMethod<[string], undefined>,
  'getActiveUserCount' : ActorMethod<[], bigint>,
  'getAllFeedbackEntriesForPrincipal' : ActorMethod<
    [Principal],
    Array<Feedback>
  >,
  'getAllPasswordEntriesFromVault' : ActorMethod<[], Array<PasswordEntry>>,
  'getAllSecureNotesFromVault' : ActorMethod<[], Array<SecureNote>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPasswordEntryFromVault' : ActorMethod<[string], PasswordEntry>,
  'getSecureNoteFromVault' : ActorMethod<[string], SecureNote>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserProfileFromVault' : ActorMethod<[], UserProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitFeedbackEntry' : ActorMethod<[string, bigint], undefined>,
  'updateUserProfileInVault' : ActorMethod<[string, Language], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];