/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Username = IDL.Text;
export const StrongPassword = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Feedback = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PasswordEntry = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'username' : Username,
  'blob' : IDL.Opt(ExternalBlob),
  'password' : StrongPassword,
  'notes' : IDL.Text,
});
export const SecureNote = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'blob' : IDL.Opt(ExternalBlob),
});
export const Language = IDL.Variant({
  'en' : IDL.Null,
  'nl' : IDL.Null,
  'pl' : IDL.Null,
  'th' : IDL.Null,
  'zh' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'language' : Language,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPasswordEntryToVault' : IDL.Func(
      [
        IDL.Text,
        Username,
        StrongPassword,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'addSecureNoteToVault' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePasswordEntryFromVault' : IDL.Func([IDL.Text], [], []),
  'deleteSecureNoteFromVault' : IDL.Func([IDL.Text], [], []),
  'getActiveUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllFeedbackEntriesForPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Feedback)],
      ['query'],
    ),
  'getAllPasswordEntriesFromVault' : IDL.Func(
      [],
      [IDL.Vec(PasswordEntry)],
      ['query'],
    ),
  'getAllSecureNotesFromVault' : IDL.Func([], [IDL.Vec(SecureNote)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPasswordEntryFromVault' : IDL.Func(
      [IDL.Text],
      [PasswordEntry],
      ['query'],
    ),
  'getSecureNoteFromVault' : IDL.Func([IDL.Text], [SecureNote], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserProfileFromVault' : IDL.Func([], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFeedbackEntry' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'updateUserProfileInVault' : IDL.Func(
      [IDL.Text, Language],
      [UserProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Username = IDL.Text;
  const StrongPassword = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Feedback = IDL.Record({ 'message' : IDL.Text, 'timestamp' : IDL.Int });
  const PasswordEntry = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'username' : Username,
    'blob' : IDL.Opt(ExternalBlob),
    'password' : StrongPassword,
    'notes' : IDL.Text,
  });
  const SecureNote = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'blob' : IDL.Opt(ExternalBlob),
  });
  const Language = IDL.Variant({
    'en' : IDL.Null,
    'nl' : IDL.Null,
    'pl' : IDL.Null,
    'th' : IDL.Null,
    'zh' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'language' : Language });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPasswordEntryToVault' : IDL.Func(
        [
          IDL.Text,
          Username,
          StrongPassword,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'addSecureNoteToVault' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePasswordEntryFromVault' : IDL.Func([IDL.Text], [], []),
    'deleteSecureNoteFromVault' : IDL.Func([IDL.Text], [], []),
    'getActiveUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllFeedbackEntriesForPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Feedback)],
        ['query'],
      ),
    'getAllPasswordEntriesFromVault' : IDL.Func(
        [],
        [IDL.Vec(PasswordEntry)],
        ['query'],
      ),
    'getAllSecureNotesFromVault' : IDL.Func(
        [],
        [IDL.Vec(SecureNote)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPasswordEntryFromVault' : IDL.Func(
        [IDL.Text],
        [PasswordEntry],
        ['query'],
      ),
    'getSecureNoteFromVault' : IDL.Func([IDL.Text], [SecureNote], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserProfileFromVault' : IDL.Func([], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFeedbackEntry' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'updateUserProfileInVault' : IDL.Func(
        [IDL.Text, Language],
        [UserProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };