/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Username = IDL.Text;
export const StrongPassword = IDL.Text;
export const CustomField = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
  'fieldType' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FeedbackStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'read' : IDL.Null,
  'unread' : IDL.Null,
});
export const FeedbackWithPrincipal = IDL.Record({
  'id' : IDL.Nat,
  'status' : FeedbackStatus,
  'principal' : IDL.Principal,
  'adminReply' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'adminReplyTimestamp' : IDL.Opt(IDL.Int),
});
export const FeedbackLegacy = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PasswordEntry = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'username' : Username,
  'blob' : IDL.Opt(ExternalBlob),
  'password' : StrongPassword,
  'totp' : IDL.Text,
  'email' : IDL.Text,
  'customFields' : IDL.Vec(CustomField),
  'notes' : IDL.Text,
  'category' : IDL.Text,
});
export const SecureNote = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'blob' : IDL.Opt(ExternalBlob),
});
export const Language = IDL.Variant({
  'en' : IDL.Null,
  'nl' : IDL.Null,
  'pl' : IDL.Null,
  'th' : IDL.Null,
  'zh' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'language' : Language,
});
export const LoginActivity = IDL.Record({
  'principal' : IDL.Principal,
  'loginCount' : IDL.Nat,
  'lastLoginTimestamp' : IDL.Int,
});
export const PasswordHistoryEntry = IDL.Record({
  'changedAt' : IDL.Int,
  'password' : IDL.Text,
});
export const SystemStats = IDL.Record({
  'blockedUsers' : IDL.Nat,
  'totalPasswords' : IDL.Nat,
  'unreadFeedback' : IDL.Nat,
  'totalFeedback' : IDL.Nat,
  'totalNotes' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const FeedbackForUser = IDL.Record({
  'id' : IDL.Nat,
  'status' : FeedbackStatus,
  'adminReply' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'adminReplyTimestamp' : IDL.Opt(IDL.Int),
});
export const UserStats = IDL.Record({
  'noteCount' : IDL.Nat,
  'passwordCount' : IDL.Nat,
});
export const UserWithPrincipal = IDL.Record({
  'principal' : IDL.Principal,
  'isBlocked' : IDL.Bool,
  'name' : IDL.Text,
  'language' : Language,
  'noteCount' : IDL.Nat,
  'passwordCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPasswordEntryToVault' : IDL.Func(
      [
        IDL.Text,
        Username,
        StrongPassword,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(CustomField),
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'addSecureNoteToVault' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'adminDeleteFeedback' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'adminDeleteUser' : IDL.Func([IDL.Principal], [], []),
  'adminReplyFeedback' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'clearPasswordHistory' : IDL.Func([IDL.Text], [], []),
  'deletePasswordEntryFromVault' : IDL.Func([IDL.Text], [], []),
  'deleteSecureNoteFromVault' : IDL.Func([IDL.Text], [], []),
  'getActiveUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllFeedbackEntries' : IDL.Func([], [IDL.Vec(FeedbackWithPrincipal)], []),
  'getAllFeedbackEntriesForPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FeedbackLegacy)],
      ['query'],
    ),
  'getAllPasswordEntriesFromVault' : IDL.Func(
      [],
      [IDL.Vec(PasswordEntry)],
      ['query'],
    ),
  'getAllSecureNotesFromVault' : IDL.Func([], [IDL.Vec(SecureNote)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLoginActivityLog' : IDL.Func([], [IDL.Vec(LoginActivity)], ['query']),
  'getMaintenanceMode' : IDL.Func([], [IDL.Bool], ['query']),
  'getPasswordEntryFromVault' : IDL.Func(
      [IDL.Text],
      [PasswordEntry],
      ['query'],
    ),
  'getPasswordHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PasswordHistoryEntry)],
      ['query'],
    ),
  'getSecureNoteFromVault' : IDL.Func([IDL.Text], [SecureNote], ['query']),
  'getSystemAnnouncement' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
  'getUserFeedbackWithReplies' : IDL.Func([], [IDL.Vec(FeedbackForUser)], []),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserProfileFromVault' : IDL.Func([], [UserProfile], ['query']),
  'getUserStats' : IDL.Func([IDL.Principal], [UserStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'listAllUsersWithPrincipals' : IDL.Func(
      [],
      [IDL.Vec(UserWithPrincipal)],
      ['query'],
    ),
  'markFeedbackAsRead' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'markFeedbackAsResolved' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'recordLoginActivity' : IDL.Func([IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMaintenanceMode' : IDL.Func([IDL.Bool], [], []),
  'setSystemAnnouncement' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
  'submitFeedbackEntry' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updatePasswordEntryInVault' : IDL.Func(
      [
        IDL.Text,
        Username,
        StrongPassword,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(CustomField),
        IDL.Opt(ExternalBlob),
        IDL.Int,
      ],
      [],
      [],
    ),
  'updateUserProfileInVault' : IDL.Func(
      [IDL.Text, Language],
      [UserProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Username = IDL.Text;
  const StrongPassword = IDL.Text;
  const CustomField = IDL.Record({
    'value' : IDL.Text,
    'name' : IDL.Text,
    'fieldType' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FeedbackStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'read' : IDL.Null,
    'unread' : IDL.Null,
  });
  const FeedbackWithPrincipal = IDL.Record({
    'id' : IDL.Nat,
    'status' : FeedbackStatus,
    'principal' : IDL.Principal,
    'adminReply' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'adminReplyTimestamp' : IDL.Opt(IDL.Int),
  });
  const FeedbackLegacy = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PasswordEntry = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'username' : Username,
    'blob' : IDL.Opt(ExternalBlob),
    'password' : StrongPassword,
    'totp' : IDL.Text,
    'email' : IDL.Text,
    'customFields' : IDL.Vec(CustomField),
    'notes' : IDL.Text,
    'category' : IDL.Text,
  });
  const SecureNote = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'blob' : IDL.Opt(ExternalBlob),
  });
  const Language = IDL.Variant({
    'en' : IDL.Null,
    'nl' : IDL.Null,
    'pl' : IDL.Null,
    'th' : IDL.Null,
    'zh' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'language' : Language });
  const LoginActivity = IDL.Record({
    'principal' : IDL.Principal,
    'loginCount' : IDL.Nat,
    'lastLoginTimestamp' : IDL.Int,
  });
  const PasswordHistoryEntry = IDL.Record({
    'changedAt' : IDL.Int,
    'password' : IDL.Text,
  });
  const SystemStats = IDL.Record({
    'blockedUsers' : IDL.Nat,
    'totalPasswords' : IDL.Nat,
    'unreadFeedback' : IDL.Nat,
    'totalFeedback' : IDL.Nat,
    'totalNotes' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const FeedbackForUser = IDL.Record({
    'id' : IDL.Nat,
    'status' : FeedbackStatus,
    'adminReply' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'adminReplyTimestamp' : IDL.Opt(IDL.Int),
  });
  const UserStats = IDL.Record({
    'noteCount' : IDL.Nat,
    'passwordCount' : IDL.Nat,
  });
  const UserWithPrincipal = IDL.Record({
    'principal' : IDL.Principal,
    'isBlocked' : IDL.Bool,
    'name' : IDL.Text,
    'language' : Language,
    'noteCount' : IDL.Nat,
    'passwordCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPasswordEntryToVault' : IDL.Func(
        [
          IDL.Text,
          Username,
          StrongPassword,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(CustomField),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'addSecureNoteToVault' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'adminDeleteFeedback' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'adminDeleteUser' : IDL.Func([IDL.Principal], [], []),
    'adminReplyFeedback' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'clearPasswordHistory' : IDL.Func([IDL.Text], [], []),
    'deletePasswordEntryFromVault' : IDL.Func([IDL.Text], [], []),
    'deleteSecureNoteFromVault' : IDL.Func([IDL.Text], [], []),
    'getActiveUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllFeedbackEntries' : IDL.Func(
        [],
        [IDL.Vec(FeedbackWithPrincipal)],
        [],
      ),
    'getAllFeedbackEntriesForPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FeedbackLegacy)],
        ['query'],
      ),
    'getAllPasswordEntriesFromVault' : IDL.Func(
        [],
        [IDL.Vec(PasswordEntry)],
        ['query'],
      ),
    'getAllSecureNotesFromVault' : IDL.Func(
        [],
        [IDL.Vec(SecureNote)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLoginActivityLog' : IDL.Func([], [IDL.Vec(LoginActivity)], ['query']),
    'getMaintenanceMode' : IDL.Func([], [IDL.Bool], ['query']),
    'getPasswordEntryFromVault' : IDL.Func(
        [IDL.Text],
        [PasswordEntry],
        ['query'],
      ),
    'getPasswordHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PasswordHistoryEntry)],
        ['query'],
      ),
    'getSecureNoteFromVault' : IDL.Func([IDL.Text], [SecureNote], ['query']),
    'getSystemAnnouncement' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
    'getUserFeedbackWithReplies' : IDL.Func([], [IDL.Vec(FeedbackForUser)], []),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserProfileFromVault' : IDL.Func([], [UserProfile], ['query']),
    'getUserStats' : IDL.Func([IDL.Principal], [UserStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'listAllUsersWithPrincipals' : IDL.Func(
        [],
        [IDL.Vec(UserWithPrincipal)],
        ['query'],
      ),
    'markFeedbackAsRead' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'markFeedbackAsResolved' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'recordLoginActivity' : IDL.Func([IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMaintenanceMode' : IDL.Func([IDL.Bool], [], []),
    'setSystemAnnouncement' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
    'submitFeedbackEntry' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updatePasswordEntryInVault' : IDL.Func(
        [
          IDL.Text,
          Username,
          StrongPassword,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(CustomField),
          IDL.Opt(ExternalBlob),
          IDL.Int,
        ],
        [],
        [],
      ),
    'updateUserProfileInVault' : IDL.Func(
        [IDL.Text, Language],
        [UserProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };